# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\subwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_SubWindow(object):
    def setupUi(self):
        SubWindow = QtWidgets.QMainWindow()
        SubWindow.setObjectName("SubWindow")
        SubWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(SubWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.info_title = QtWidgets.QLabel(self.centralwidget)
        self.info_title.setGeometry(QtCore.QRect(120, 50, 420, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.info_title.setFont(font)
        self.info_title.setObjectName("info_title")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 380, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        
        self.level_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.level_edit.setGeometry(QtCore.QRect(260, 120, 280, 40))
        self.level_edit.setObjectName("level_edit")
        
        self.duration_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.duration_edit.setGeometry(QtCore.QRect(260, 180, 280, 40))
        self.duration_edit.setObjectName("duration_edit")
        
        self.timeout_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.timeout_edit.setGeometry(QtCore.QRect(260, 240, 280, 40))
        self.timeout_edit.setObjectName("timeout_edit")
        
        self.delay_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.delay_edit.setGeometry(QtCore.QRect(260, 300, 280, 40))
        self.delay_edit.setObjectName("delay_edit")
        
        SubWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SubWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName("menubar")
        SubWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SubWindow)
        self.statusbar.setObjectName("statusbar")
        SubWindow.setStatusBar(self.statusbar)

        self.level_edit.setVisible(False)
        self.duration_edit.setVisible(False)
        self.timeout_edit.setVisible(False)
        self.delay_edit.setVisible(False)

        self.retranslateUi(SubWindow)
        QtCore.QMetaObject.connectSlotsByName(SubWindow)

    def create_config_item(self, config=["timeout", "delay"]):
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)

        editbox_table = {
            "level" : [self.level_edit, "255"],
            "duration" : [self.duration_edit, "50"],
            "timeout" : [self.timeout_edit, "1000"],
            "delay" : [self.delay_edit, "0"]
        } 

        for i in range(len(config)):
            
            # Text
            label = QtWidgets.QLabel(self.centralwidget)
            label.setFont(font)
            label.setText(config[i])
            label.setGeometry(QtCore.QRect(120, 120 + i*60, 140, 40))

            # Edit
            edit = editbox_table[config[i]][0]
            edit.setPlaceholderText(editbox_table[config[i]][1])
            edit.setVisible(True) 

    
    def show_window(self, temp_pair_table):
        self.info_title.setText(f"配對裝置: endpoint {temp_pair_table[0]}, 配對目標: endpoint {temp_pair_table[1]}")
        self.show()

    def retranslateUi(self, SubWindow):
        _translate = QtCore.QCoreApplication.translate
        SubWindow.setWindowTitle(_translate("SubWindow", "MainWindow"))
        self.pushButton.setText(_translate("SubWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubWindow = QtWidgets.QMainWindow()
    ui = Ui_SubWindow()
    ui.setupUi(SubWindow)
    SubWindow.show()
    sys.exit(app.exec_())
